version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/**"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: BAU
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pre-commit"
    directories:
      - "/"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
    groups:
      pre-commit-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directories:
      - "/solutions/integration-tests"
      - "/solutions/local-aws/local-kms"
      - "/solutions/local-aws/floci"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: BAU
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
    groups:
      docker-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: pip
    directories:
      - "/**"
    schedule:
      interval: "cron"
      cronjob: "0 3 1,15 * *"
      time: "03:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 7
    labels:
      - dependabot
      - dependencies
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"
