default_install_hook_types: [commit-msg, pre-commit, pre-push]
fail_fast: true

repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # pragma: allowlist secret
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # pragma: allowlist secret
    hooks:
      - id: detect-private-key
        stages: [pre-commit]
      - id: no-commit-to-branch
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]

  - repo: https://github.com/Yelp/detect-secrets
    rev: 5e141933554a0b74e7341841f318be21e895339c # pragma: allowlist secret
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: check-types
        name: Check types
        entry: npm run check-types
        language: system
        exclude: .*
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: check-formatting
        name: Check formatting
        entry: npm run format
        language: system
        exclude: .*
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: e3eebf65325ccc992422292cb7a4baee967cf815 # pragma: allowlist secret
    hooks:
      - id: zizmor
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npm run eslint
        language: system
        exclude: .*
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: sam-validate
        name: SAM validate
        entry: npm run sam-validate
        language: system
        exclude: .*
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: knip
        name: Knip
        entry: npm run knip
        language: system
        exclude: .*
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: bb451c5c4ae66a948eb8af386d0079e16a8ca0aa # pragma: allowlist secret
    hooks:
      - id: checkov
        entry: npm run checkov
        always_run: true
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: test
        name: Test
        entry: npm run test:coverage
        language: system
        exclude: .*
        always_run: true
        pass_filenames: false
        stages: [pre-push]
