sonar.organization=govuk-one-login
# CHANGEME change this to your Sonar project key
sonar.projectKey=govuk-one-login_lambda-frontend-starter
# CHANGEME change this to your Sonar project name
sonar.projectName=lambda-frontend-starter

sonar.host.url=https://sonarcloud.io

sonar.sources=solutions/
sonar.tests=solutions/
sonar.test.inclusions=**/*.test.ts
sonar.coverage.exclusions=solutions/integration-tests/**,solutions/frontend/rolldown.config.ts,solutions/frontend/rolldown.local.config.ts,solutions/frontend/src/local.ts,solutions/frontend/src/lambda.ts,solutions/frontend/src/index.ts

sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info