# Despite what SonarQube says both the tag and sha digest are needed:
# the digest pins the exact image for reproducibility,
# the tag allows Dependabot to evaluate version constraints
FROM floci/floci:latest@sha256:eab36252ea43a4a73928423f0372219052c5c6f87207f6c4754db14b91d6ed30

USER floci

HEALTHCHECK NONE
