name: Deploy application to dev

permissions: {}

on:
  workflow_dispatch: # checkov:skip=CKV_GHA_7: workflow intentionally allows ref selection for dev deployments
    inputs:
      refType:
        type: choice
        description: "Find branch name, commit SHA, or tag?"
        options:
          - Branch name
          - Commit SHA
          - Tag
        default: Branch name
      gitRef:
        description: "Input branch name, commit SHA, or tag"
        required: true
        type: string
        default: main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish-integration-tests-image:
    if: false # CHANGEME remove this when you are ready to deploy to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d
        with:
          # CHANGEME add a GitHub secret called DEV_PIPELINE_GH_ACTIONS_ROLE_ARN
          # with the value of the GitHubActionsRoleArn output from your dev pipeline stack
          # see https://github.com/govuk-one-login/devplatform-deploy/tree/main/sam-deploy-pipeline
          role-to-assume: ${{ secrets.DEV_PIPELINE_GH_ACTIONS_ROLE_ARN }}
          aws-region: "eu-west-2"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64

      - name: Build & publish Docker image
        working-directory: solutions/integration-tests
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # CHANGEME add a GitHub secret called DEV_POST_DEPLOY_TESTS_IMAGE_REPOSITORY
          # with the value of the name of your dev test image repository
          # see https://github.com/govuk-one-login/devplatform-deploy/tree/main/test-image-repository
          ECR_REPOSITORY: ${{ secrets.DEV_POST_DEPLOY_TESTS_IMAGE_REPOSITORY }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

  deploy-to-dev:
    needs: publish-integration-tests-image
    if: false # CHANGEME remove this when you are ready to deploy to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
          ref: ${{ inputs.gitRef }}

      - name: Set commit SHA
        if: github.event.inputs.refType == 'Commit SHA'
        run: echo GIT_REF_SHA=${GIT_REF} >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set commit SHA by branch name
        if: github.event.inputs.refType == 'Branch name'
        run: echo GIT_REF_SHA=$(git log -1 ${GIT_REF} --pretty=format:%H) >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set commit SHA by tag
        if: github.event.inputs.refType == 'Tag'
        run: echo GIT_REF_SHA=$(git rev-list -n 1 ${GIT_REF}) >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set current datetime
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .nvmrc

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@517a711dbcd0e402f90c77e7e2f81e849156e31d
        with:
          # CHANGEME add a GitHub secret called DEV_PIPELINE_GH_ACTIONS_ROLE_ARN
          # with the value of the GitHubActionsRoleArn output from your dev pipeline stack
          # see https://github.com/govuk-one-login/devplatform-deploy/tree/main/sam-deploy-pipeline
          role-to-assume: ${{ secrets.DEV_PIPELINE_GH_ACTIONS_ROLE_ARN }}
          aws-region: "eu-west-2"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Deploy
        uses: govuk-one-login/devplatform-upload-action@64e46134b4108ebfa1cf2a64fee00782f8e2e8cf
        with:
          # CHANGEME add a GitHub secret called DEV_PIPELINE_SOURCE_BUCKET_NAME
          # with the value of the GitHubArtifactSourceBucketName output from your dev pipeline stack
          # see https://github.com/govuk-one-login/devplatform-deploy/tree/main/sam-deploy-pipeline
          artifact-bucket-name: ${{ secrets.DEV_PIPELINE_SOURCE_BUCKET_NAME }}
          # CHANGEME add a GitHub secret called DEV_SIGNING_PROFILE_NAME
          # with the value of the SigningProfileName output from your dev signer stack
          # see https://github.com/govuk-one-login/devplatform-deploy/tree/main/signer
          signing-profile-name: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
          working-directory: ./solutions/app-infra
          template-file: .aws-sam/build/template.yaml
