name: Local tests (integration)

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  local-tests-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --ignore-scripts && cd solutions/integration-tests && npm ci --ignore-scripts

      - name: Configure environment variables
        run: |
          cd solutions/frontend
          cat > .env.integration-tests << 'EOF'
          ENVIRONMENT=local
          NODE_ENV=production
          USE_LOCAL_AWS=1
          SESSIONS_SIGNER=localsessionsignerwhichmustbeatleast32chars
          SESSIONS_TABLE_NAME=changeme-SessionStore # replace changeme with the value of AWS::StackName in solutions/app-infra/template.yaml
          ROOT_DOMAIN_WITH_ENV=localhost
          AWS_REGION=eu-west-2
          LOCAL_AWS_ENDPOINT=http://localhost:4566
          LOCAL_AWS_KMS_ENDPOINT=http://localhost:4567
          LOCAL_AWS_ACCESS_KEY_ID=test
          LOCAL_AWS_ACCESS_KEY=test
          AUTH_FRONTEND_URL=https://signin.account.gov.uk
          GA4_CONTAINER_ID=GTM-FAKE
          ANALYTICS_ENABLED=1
          ANALYTICS_COOKIE_DOMAIN=localhost
          EOF

      - name: Run integration tests
        run: |
          cd solutions/integration-tests
          touch .env
          echo "PRE_OR_POST_DEPLOY=pre" >> .env
          echo "PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/" >> .env
          npm run test

      - name: Upload test results artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: always()
        with:
          name: integration-test-results
          path: solutions/integration-tests/test-results/
          retention-days: 7
